### Get all persons
GET http://fso-phonebook-backend.fly.dev/api/persons

### Get info
GET http://fso-phonebook-backend.fly.dev/info

### Get person with existing id
GET http://fso-phonebook-backend.fly.dev/api/persons/1


### Person with nonexisting id
GET http://fso-phonebook-backend.fly.dev/api/persons/1000


### Delete person with id=3
DELETE http://fso-phonebook-backend.fly.dev/api/persons/3 HTTP/1.1

### Add new person
POST http://fso-phonebook-backend.fly.dev/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "pawel",
    "number": "8"
}